export const apiRouters = {
  auth: {
    register: "/auth/register",
    login: "/auth/login",
    logout: "/auth/logout",
    me: "/auth/me",
  },
  creatorApplications: {
    index: "/admin/creator-applications",
    get: "/creator-applications/me",
    insert: "/creator-applications",
    update: "/admin/creator-applications/:id/approve",
    delete: "/admin/creator-applications/:id/reject",
  },
  creatorExams: {
    index: "/creator/exams",
    show: "/creator/exams/:id",
    insert: "/creator/exams",
    update: "/creator/exams/:id",
    insertQuestion: "/creator/exams/:id/questions",
    updateQuestion: "/creator/exams/:id/questions/:questionId",
    deleteQuestion: "/creator/exams/:id/questions/:questionId",
    submitReview: "/creator/exams/:id/submit-review",
  },
  adminExamReviews: {
    index: "/admin/exam-reviews",
    show: "/admin/exam-reviews/:id",
    approve: "/admin/exam-reviews/:id/approve",
    reject: "/admin/exam-reviews/:id/reject",
  },
  paymentMethods: {
    index: "/payment-methods",
    show: "/payment-methods/:id",
    insert: "/payment-methods",
    update: "/payment-methods/:id",
    delete: "/payment-methods/:id",
  },
  locations: {
    index: "/locations",
    show: "/locations/:id",
    insert: "/locations",
    update: "/locations/:id",
    delete: "/locations/:id",
  },
  shipments: {
    index: "/shipments",
    show: "/shipments/:id",
    insert: "/shipments",
    update: "/shipments/:id",
    editPolicy: "/shipments/:id/edit-policy",
    tracking: "/shipments/:id/tracking",
  },
  vendors: {
    index: "/vendors",
    show: "/vendors/:id",
    insert: "/vendors",
    update: "/vendors/:id",
    delete: "/vendors/:id",
    ban: "/vendors/:id/ban",
    unban: "/vendors/:id/unban",
  },
  drivers: {
    index: "/vendors/:vendorId/drivers",
    show: "/vendors/:vendorId/drivers/:id",
    insert: "/vendors/:vendorId/drivers",
    update: "/vendors/:vendorId/drivers/:id",
    delete: "/vendors/:vendorId/drivers/:id",
    ban: "/vendors/:vendorId/drivers/:id/ban",
    unban: "/vendors/:vendorId/drivers/:id/unban",
    locationHistory: "/vendors/:vendorId/drivers/:id/location-history",
  },
  routes: {
    index: "/routes",
    show: "/routes/:id",
    insert: "/routes",
    update: "/routes/:id",
    delete: "/routes/:id",
  },
  trafficSources: {
    index: "/traffic-sources",
    show: "/traffic-sources/:id",
    insert: "/traffic-sources",
    update: "/traffic-sources/:id",
    delete: "/traffic-sources/:id",
  },
  users: {
    index: "/users",
    show: "/users/:id",
    insert: "/users",
    update: "/users/:id",
    ban: "/users/:id/ban",
    resendVerification: "/users/resend-verification",
  },
  properties: {
    index: "/properties",
    show: "/properties/:id",
    insert: "/properties",
    update: "/properties/:id",
    delete: "/properties/:id",
  },
  aiSettings: {
    show: "/settings/ai",
    update: "/settings/ai",
    delete: "/settings/ai",
    test: "/settings/ai/test",
  },
  bunnySettings: {
    show: "/settings/bunny",
    update: "/settings/bunny",
    delete: "/settings/bunny",
    test: "/settings/bunny/test",
  },
  media: {
    upload: "/media/upload",
  },
  serviceCategories: {
    index: "/service-categories",
    show: "/service-categories/:id",
    insert: "/service-categories",
    update: "/service-categories/:id",
    delete: "/service-categories/:id",
    active: "/service-categories/:id/active",
  },
  deliveryMethods: {
    index: "/delivery-methods",
    show: "/delivery-methods/:id",
    insert: "/delivery-methods",
    update: "/delivery-methods/:id",
    delete: "/delivery-methods/:id",
    active: "/delivery-methods/:id/active",
  },
  physicalInspections: {
    index: "/physical-inspections",
    show: "/physical-inspections/:id",
    insert: "/physical-inspections",
    update: "/physical-inspections/:id",
    delete: "/physical-inspections/:id",
    restore: "/physical-inspections/:id/restore",
  },
  serviceTypes: {
    index: "/service-types",
    show: "/service-types/:id",
    insert: "/service-types",
    update: "/service-types/:id",
    delete: "/service-types/:id",
    active: "/service-types/:id/active",
  },
  places: {
    province: "/place/provinces",
    city: "/place/province/:provinceCode/cities",
  },
  routePrices: {
    index: "/route-prices",
    show: "/route-prices/:id",
    update: "/route-prices/:id",
  },
  cityInServices: {
    origin: "/city-in-services/origin",
    destination: "/city-in-services/destination/:id",
  },
  availableServices: {
    list: "/available-services",
    routes: "/available-routes",
  },
  shipmentConfigs: {
    show: "/shipment-configs",
  },
}
