export const queryKeys = {
  auth: {
    register: "authRegister",
    login: "authLogin",
    logout: "authLogout",
    me: "authMe",
  },
  creatorApplications: {
    index: "creatorApplicationsIndex",
    get: "creatorApplicationsGet",
    insert: "creatorApplicationsInsert",
    update: "creatorApplicationsUpdate",
    delete: "creatorApplicationsDelete",
  },
  emailJobs: {
    template: "emailJobsTemplate",
    insert: "emailJobsInsert",
  },
  paymentMethods: {
    index: "paymentMethodsIndex",
    get: "paymentMethodsGet",
    insert: "paymentMethodsInsert",
    update: "paymentMethodsUpdate",
    delete: "paymentMethodsDelete",
  },
  locations: {
    index: "locationsIndex",
    get: "locationsGet",
    insert: "locationsInsert",
    update: "locationsUpdate",
    delete: "locationsDelete",
  },
  shipments: {
    index: "shipmentsIndex",
    get: "shipmentsGet",
    insert: "shipmentsInsert",
    update: "shipmentsUpdate",
    editPolicy: "shipmentsEditPolicy",
    delete: "shipmentsDelete",
  },
  vendors: {
    index: "vendorsIndex",
    get: "vendorsGet",
    insert: "vendorsInsert",
    update: "vendorsUpdate",
    delete: "vendorsDelete",
  },
  drivers: {
    index: "driversIndex",
    get: "driversGet",
    insert: "driversInsert",
    update: "driversUpdate",
    delete: "driversDelete",
    ban: "driversBan",
    unban: "driversUnban",
    locationHistory: "driversLocationHistory",
  },
  routes: {
    index: "routesIndex",
    get: "routesGet",
    insert: "routesInsert",
    update: "routesUpdate",
    delete: "routesDelete",
  },
  trafficSources: {
    index: "trafficSourcesIndex",
    get: "trafficSourcesGet",
    insert: "trafficSourcesInsert",
    update: "trafficSourcesUpdate",
    delete: "trafficSourcesDelete",
  },
  users: {
    index: "usersIndex",
    get: "usersGet",
    insert: "usersInsert",
    update: "usersUpdate",
    ban: "usersBan",
    resendVerification: "usersResendVerification",
  },
  properties: {
    index: "propertiesIndex",
    get: "propertiesGet",
    insert: "propertiesInsert",
    update: "propertiesUpdate",
    delete: "propertiesDelete",
  },
  aiSettings: {
    index: "aiSettingsIndex",
    get: "aiSettingsGet",
    update: "aiSettingsUpdate",
    delete: "aiSettingsDelete",
    test: "aiSettingsTest",
  },
  bunnySettings: {
    index: "bunnySettingsIndex",
    get: "bunnySettingsGet",
    update: "bunnySettingsUpdate",
    delete: "bunnySettingsDelete",
    test: "bunnySettingsTest",
  },
  serviceCategories: {
    index: "serviceCategoriesIndex",
    get: "serviceCategoriesGet",
    insert: "serviceCategoriesInsert",
    update: "serviceCategoriesUpdate",
    delete: "serviceCategoriesDelete",
    active: "serviceCategoriesActive",
  },
  deliveryMethods: {
    index: "deliveryMethodsIndex",
    get: "deliveryMethodsGet",
    insert: "deliveryMethodsInsert",
    update: "deliveryMethodsUpdate",
    delete: "deliveryMethodsDelete",
    active: "deliveryMethodsActive",
  },
  physicalInspections: {
    index: "physicalInspectionsIndex",
    get: "physicalInspectionsGet",
    insert: "physicalInspectionsInsert",
    update: "physicalInspectionsUpdate",
    delete: "physicalInspectionsDelete",
    restore: "physicalInspectionsRestore",
  },
  serviceTypes: {
    index: "serviceTypesIndex",
    get: "serviceTypesGet",
    insert: "serviceTypesInsert",
    update: "serviceTypesUpdate",
    delete: "serviceTypesDelete",
    active: "serviceTypesActive",
  },
  places: {
    provinces: "placeProvinces",
    cities: "placeCities",
  },
  routePrices: {
    index: "routePricesIndex",
    get: "routePricesGet",
    update: "routePricesUpdate",
  },
  cityInServices: {
    origin: "cityInServicesOrigin",
    destination: "cityInServicesDestination",
  },
  availableServices: {
    list: "availableServicesList",
    routes: "availableRoutesList",
  },
  shipmentConfigs: {
    get: "shipmentConfigsGet",
  },
}
